import { c as create_ssr_component } from "../../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '.title.svelte-1ttqad1{margin-bottom:3vw;color:black;font-size:3vw;font-family:"Unica One", sans-serif;font-weight:500;letter-spacing:1px;word-wrap:break-word}.submitbutton.svelte-1ttqad1{margin-top:3vw}.logincontainer.svelte-1ttqad1{width:20vw;height:30vw;padding:1vw;border-radius:1vw;background-color:white;border:#FF4D2D 5px solid}.fullsize.svelte-1ttqad1{width:100vw;height:100vh}.center.svelte-1ttqad1{display:flex;flex-wrap:wrap;justify-content:center;align-items:center}.inp.svelte-1ttqad1{width:100%;height:3vw;margin-top:1vw;margin-bottom:1vw;border-radius:5px;border:#FF4D2D 2px solid;padding-left:5%}.svelte-1ttqad1::placeholder{color:black;opacity:0.8;font-family:"Open Sans", sans-serif}.label.svelte-1ttqad1{width:100%;color:black;font-size:1vw;font-family:"Open Sans", sans-serif;font-weight:500;letter-spacing:1px;word-wrap:break-word}.submitbutton.svelte-1ttqad1{width:10vw;height:3vw;border-radius:0.75vw;border:none;background-color:#FF4D2D;color:white;font-size:1.5vw;font-family:"Unica One", sans-serif;font-weight:500;letter-spacing:1px;word-wrap:break-word}body{padding:0;margin:0;overscroll-behavior-y:none;overscroll-behavior-x:none}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<link rel="preconnect" href="https://fonts.googleapis.com" class="svelte-1ttqad1"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin class="svelte-1ttqad1"> <link href="https://fonts.googleapis.com/css2?family=Unica+One&display=swap" rel="stylesheet" class="svelte-1ttqad1"> <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" class="svelte-1ttqad1">  <div class="fullsize center svelte-1ttqad1" data-svelte-h="svelte-12y4fx8"><div class="logincontainer center svelte-1ttqad1"><div class="center svelte-1ttqad1"><div class="title svelte-1ttqad1">SIGN IN</div> <form class="center svelte-1ttqad1" method="POST" action="?/login"><div style="width: 100%; padding-bottom: 1vw" class="svelte-1ttqad1"><label class="center svelte-1ttqad1" style="width: 100%"><div class="label svelte-1ttqad1">Email</div> <input class="inp svelte-1ttqad1" id="email" name="email" type="email" value="" placeholder="Email" required></label></div> <div style="width: 100%" class="svelte-1ttqad1"><label class="center svelte-1ttqad1" for="password" style="width: 100%"><div class="label svelte-1ttqad1">Password</div> <input class="inp svelte-1ttqad1" id="password" type="password" value="" name="password" placeholder="Password" required></label></div> <div class="submits svelte-1ttqad1"><button class="submitbutton svelte-1ttqad1" id="submit" type="submit">LOGIN</button></div></form></div></div> </div>`;
});
export {
  Page as default
};
