import { c as create_ssr_component, d as add_attribute, v as validate_component } from "../../../chunks/ssr.js";
import { M as Menu } from "../../../chunks/Menu.js";
const bannerbg = "/_app/immutable/assets/bannerbg.bfaee57b.png";
const consulting = "/_app/immutable/assets/consulting.ebb335c8.png";
const hardware = "/_app/immutable/assets/hardware.feb59954.png";
const marketing = "/_app/immutable/assets/marketing.0849b00c.png";
const software = "/_app/immutable/assets/software.07878aba.png";
const sponsorr = "/_app/immutable/assets/sponsorr.cc3ee97e.png";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '.labelbox.svelte-bh2t6p{position:absolute;top:60%;height:25%;width:100%;background-color:rgba(255, 39, 0, 0.80);color:white;font-size:5vh;font-family:"Unica One", sans-serif;font-weight:400;line-height:75px;letter-spacing:3.50px;word-wrap:break-word;text-align:center}.stimage.svelte-bh2t6p{height:100%;filter:brightness(50%)}.imgbox.svelte-bh2t6p{position:relative;display:flex;justify-content:center;align-items:center;width:37%;height:100%;margin-right:3%;overflow:hidden;border-radius:5vh}.textinternal.svelte-bh2t6p{padding:3vw;color:black;font-size:1.4vw;font-family:"Open Sans", sans-serif;font-weight:300;line-height:150%;letter-spacing:0.90px;word-wrap:break-word\n    }.textbox.svelte-bh2t6p{width:60%;height:100%;background-color:#D9D9D9;border-radius:5vh;display:flex;align-items:center}.stentry.svelte-bh2t6p{display:flex;justify-content:center;width:90%;padding-left:5%;padding-right:5%;margin-top:10vh;height:40vh}.internaltxt.svelte-bh2t6p{color:black;font-size:200%;font-family:"Unica One", cursive;font-weight:400;line-height:75px;letter-spacing:6.65px;word-wrap:break-word;background-color:rgba(255, 255, 255, 0.6);position:absolute;top:0;z-index:99;height:100%;width:90%;display:flex;justify-content:center;text-align:center;padding-top:2%;padding-left:5%;padding-right:5%}.color.svelte-bh2t6p{background-color:rgba(250, 250, 250, 0.98)}.text.svelte-bh2t6p{color:black;font-size:3vh;font-family:"Open Sans", sans-serif;font-weight:300;line-height:130%;letter-spacing:1px;word-wrap:break-word\n    }.list.svelte-bh2t6p{list-style-type:decimal}.center.svelte-bh2t6p{justify-content:center}.page.svelte-bh2t6p{display:block;position:relative;margin:5vw\n    }.stcontainer.svelte-bh2t6p{position:relative;margin:0;display:flex;flex-wrap:wrap}.st.svelte-bh2t6p{position:relative;aspect-ratio:4/3;width:60vw;margin:5vw;border-radius:5vh;overflow:hidden}.abouttxt.svelte-bh2t6p{position:relative;height:auto;padding:0.1vh 5vw 5vh;margin:0;border-bottom:#D9D9D9 1vw solid}.imgwrapper.svelte-bh2t6p{display:flex;position:absolute;justify-content:center;overflow:hidden}.bannersize.svelte-bh2t6p{width:100vw;height:47vh}.bannerimg.svelte-bh2t6p{display:block;float:left;padding:0;margin:0}.title.svelte-bh2t6p{position:absolute;top:0;left:0;z-index:20;color:white;font-size:15vh;font-family:"Unica One", cursive;font-weight:400;line-height:16vh;letter-spacing:6.65px;word-wrap:break-word;display:flex;justify-content:center;align-items:center;text-align:center;background-color:rgba(0, 0, 0, 0.5)}body{padding:0;margin:0;overscroll-behavior-y:none;overscroll-behavior-x:none}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Unica+One&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">  <div class="banner bannersize svelte-bh2t6p" data-svelte-h="svelte-1320i2c"><div class="imgwrapper bannersize center svelte-bh2t6p"><img class="bannerimg svelte-bh2t6p"${add_attribute("src", bannerbg, 0)}> <img class="bannerimg svelte-bh2t6p"${add_attribute("src", bannerbg, 0)}> <img class="bannerimg svelte-bh2t6p"${add_attribute("src", bannerbg, 0)}></div> <div class="title bannersize svelte-bh2t6p">About the Club</div></div> <div class="page svelte-bh2t6p"><div class="abouttxt color text svelte-bh2t6p" data-svelte-h="svelte-n6te3s"><ul class="list svelte-bh2t6p"><li>Build a human carrying VTOL aircraft by 2026</li> <li>Grow the Berkeley aviation ecosystem, specifically targeting urban air mobility</li> <li>Provide hands on engineering and business experiences for our members</li></ul>
        If any of our 3 goals pique your interest, you may be a great fit for one of our subteams!</div> ${`<div class="stcontainer center color svelte-bh2t6p" data-svelte-h="svelte-1c67h4g"><div class="stentry svelte-bh2t6p"><div class="imgbox svelte-bh2t6p"><img class="stimage svelte-bh2t6p"${add_attribute("src", hardware, 0)}> <div class="labelbox svelte-bh2t6p">Hardware</div></div> <div class="textbox svelte-bh2t6p"></div></div> <div class="stentry svelte-bh2t6p"><div class="imgbox svelte-bh2t6p"><img class="stimage svelte-bh2t6p"${add_attribute("src", software, 0)}> <div class="labelbox svelte-bh2t6p">Software</div></div> <div class="textbox svelte-bh2t6p"><div class="textinternal svelte-bh2t6p">The software subteam ensures seamless aircraft operations, managing flight control,
                    autonomy, and mission planning. It offers an intuitive remote piloting and in-flight
                    piloting interfaces, logs flight telemetry data, manages on-board systems and prioritizes
                    safety with fail-safe mechanisms. The software subsystem also handles firmware updates and
                    maintenance are handled for optimal performance.</div></div></div> <div class="stentry svelte-bh2t6p"><div class="imgbox svelte-bh2t6p"><img class="stimage svelte-bh2t6p"${add_attribute("src", consulting, 0)}> <div class="labelbox svelte-bh2t6p">Consulting</div></div> <div class="textbox svelte-bh2t6p"></div></div> <div class="stentry svelte-bh2t6p"><div class="imgbox svelte-bh2t6p"><img class="stimage svelte-bh2t6p"${add_attribute("src", marketing, 0)}> <div class="labelbox svelte-bh2t6p">Marketing</div></div> <div class="textbox svelte-bh2t6p"><div class="textinternal svelte-bh2t6p">The business and operation subteams drive the club’s success by handling aspects
                    such as sponsorship, marketing, finance, and social media. They secure sponsorships,
                    plan marketing strategies, manage budgets, and curate engaging content for the club&#39;s
                    social media platforms like Instagram. By fostering partnerships and optimizing resources,
                    they ensure the club&#39;s growth and stability.</div></div></div> <div class="stentry svelte-bh2t6p"><div class="imgbox svelte-bh2t6p"><img class="stimage svelte-bh2t6p"${add_attribute("src", sponsorr, 0)}> <div class="labelbox svelte-bh2t6p">Sponsor Relations</div></div> <div class="textbox svelte-bh2t6p"><div class="textinternal svelte-bh2t6p">The business and operation subteams drive the club’s success by handling aspects
                    such as sponsorship, marketing, finance, and social media. They secure sponsorships,
                    plan marketing strategies, manage budgets, and curate engaging content for the club&#39;s
                    social media platforms like Instagram. By fostering partnerships and optimizing resources,
                    they ensure the club&#39;s growth and stability.</div></div></div></div>`} ${``}</div> ${validate_component(Menu, "Menu").$$render($$result, { includeMainLogo: false }, {}, {})}`;
});
export {
  Page as default
};
